### ISSUE TITLE
Swap Axis Augmentation

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/pytorch-yolo-v2-v3#17]
https://github.com/yjh0410/pytorch-yolo-v2-v3/blob/550661313e36d86bdfa2e4d5dc2a3b5ece411e79/utils/augmentations.py#L350-L373

I think, in the real application, there is no case that process swapped axis image. So, I think this augmentation may harm the model's performance.

 

What do you think of this augmentation?

**Comment by yjh0410** [comment]
Whatever RGB, BGR or other color formats,  it only affects the color of  of an object’s appearance. Human can recognize them no matter what their color is. Based on this augmentation trick, our detector could become more robust to color change.

**Comment by developer0hye** [comment]
@yjh0410 
Yeah, I think so. So, I agreed with color augmentation on HSV domain. But, swapping axis is a little bit strange to me. If our model needs to learn the traffic light, I think the swapping axis would make errors.    

Thanks for your opinion!

**Comment by yjh0410** [comment]
yeah,your're right. If we care more about the internal property of objects，it might be not suitable to shuflle the color channel. As for a general object detector， Swaping the axis is usually a helpful trick. To be honest，I haven't try to close this trick during training, so maybe I should do it when I want to train the model next time to see whether it really works.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 下午4:29
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Swap Axis Augmentation (#17)





 
@yjh0410
 Yeah, I think so. So, I agreed with color augmentation on HSV domain. But, swapping axis is a little bit strange to me. If our model needs to learn the traffic light, I think the swapping axis would make errors.
 
Thanks for your opinion!

**Comment by developer0hye** [comment]
@yjh0410 
Thanks!
