### ISSUE TITLE
Random Crash during Training

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/pytorch-yolo-v2-v3#18]
# My environment
GPU: gtx1080ti
Cuda: 9.2
Cudnn: not download

The program crashes during training sometimes, have you ever experienced the crash?

**Comment by yjh0410** [comment]
Sorry, I didn't have this problem. Maybe you can watch the memory usage or GPU power consumption during training stage.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 上午10:58
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yjh0410/pytorch-yolo-v2-v3] Random Crash during Training (#18)





 
My environment
 
GPU: gtx1080ti
 Cuda: 9.2
 Cudnn: not download
 
The program crashes during training sometimes, have you ever experienced the crash?

**Comment by developer0hye** [comment]
@yjh0410 
Thank you for the reply!
