### ISSUE TITLE
Hyper parameters for Training

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/pytorch-yolo-v2-v3#19]
Is the default value of args.* your hyper parameters for training?

**Comment by yjh0410** [comment]
Yes, except argument "batch_size" which should be set as 32 not 64.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 下午2:15
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yjh0410/pytorch-yolo-v2-v3] Hyper parameters for Training (#19)





 
Is the default value of args.* your hyper parameters for training?

**Comment by developer0hye** [comment]
@yjh0410 
Thanks!
