### ISSUE TITLE
Training with different IGNORE_THRESH

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/pytorch-yolo-v2-v3#24]
https://github.com/yjh0410/pytorch-yolo-v2-v3/blob/e18c5671dcfac59038717b262e2729f9f0a05fcb/tools.py#L8

Have you ever trained the model with different IGNORE_THRESH like 0.7?

I know original YOLOv3 used 0.7.

**Comment by yjh0410** [comment]
You remind me...
I adopt a different method : I assign any anchor box whose IOU is higher than ignore thresh(I set it as 0.5), so sometime there are multi anchor boxes assigned with a groundtruth box. But origin YOLO-v3 assigns only one anchor box whose IOU is the hightest. I planned to try this, but I forgot.&nbsp;
Also, I didn’t train it with different ig_thresh.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月21日(星期六) 晚上7:24
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yjh0410/pytorch-yolo-v2-v3] Training with different IGNORE_THRESH (#24)





 
https://github.com/yjh0410/pytorch-yolo-v2-v3/blob/e18c5671dcfac59038717b262e2729f9f0a05fcb/tools.py#L8
 
Have you ever trained the model with different IGNORE_THRESH like 0.7?
 
I know original YOLOv3 used 0.7.

**Comment by developer0hye** [comment]
@yjh0410 
Ah Okay, I understand! The usage of IGNORE_THRESH is different from the threshold used in YOLOv3.  Right?

**Comment by yjh0410** [comment]
Yes. And I trained my yolov3 with ig_threh 0.7 just now. Wait for good news, haha!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月21日(星期六) 晚上8:16
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Training with different IGNORE_THRESH (#24)





 
@yjh0410
 Ah Okay, I understand! The usage of IGNORE_THRESH is different from the threshold used in YOLOv3.  Right?

**Comment by developer0hye** [comment]
@yjh0410 
Thank you! which GPU do you use for training?!

**Comment by yjh0410** [comment]
Always one TITAN RTX.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月21日(星期六) 晚上8:39
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Training with different IGNORE_THRESH (#24)





 
@yjh0410
 Thank you! which GPU do you use for training?!

**Comment by developer0hye** [comment]
Great!
