### ISSUE TITLE
Tiny Backbone Structure

### ISSUE THREAD

**Issue by developer0hye** [yjh0410/pytorch-yolo-v2-v3#26]
https://github.com/yjh0410/pytorch-yolo-v2-v3/blob/e18c5671dcfac59038717b262e2729f9f0a05fcb/backbone/darknet.py#L161-L227

Why do you replace the MaxPooling with strided convolution??

I think that convolution has more complexity than MaxPooling.

**Comment by yjh0410** [comment]
In origin YOLO-v3, it does so. I just follow it.
I have done some experiments on CIFAR-10, and I found that stride-2 conv is better than pooling with the same parameters.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月22日(星期天) 中午11:07
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yjh0410/pytorch-yolo-v2-v3] Tiny Backbone Structure (#26)





 
https://github.com/yjh0410/pytorch-yolo-v2-v3/blob/e18c5671dcfac59038717b262e2729f9f0a05fcb/backbone/darknet.py#L161-L227
 
Why do you replace the MaxPooling with strided convolution??
 
I think that convolution has more complexity than MaxPooling.

**Comment by developer0hye** [comment]
@yjh0410  Thanks!
